import {
  LayoutDashboard,
  CalendarDays,
  Users2,
  PanelsTopLeft,
  Megaphone,
  ShieldCheck,
  ServerCog,
  Settings2,
} from "lucide-react";

import type { AdminNavEntry, AdminNavLink, SidebarMetric } from "../types";

export const adminNavEntries: AdminNavEntry[] = [
  { type: "section", id: "ops", label: "실시간 운영" },
  {
    type: "link",
    id: "dashboard",
    label: "라이브 운영 허브",
    description: "전체 지표·알림·태스크",
    icon: LayoutDashboard,
    path: "/admin",
    badge: { label: "LIVE", tone: "alert" },
    title: "오늘의 운영 현황",
    subtitle: "실시간 활동 피드와 핵심 KPI로 운영 우선순위를 결정합니다.",
  },
  { type: "section", id: "field", label: "매치 운영" },
  {
    type: "link",
    id: "matches",
    label: "매치 스케줄",
    description: "진행·예정·현장 이슈",
    icon: CalendarDays,
    path: "/admin/matches",
    badge: { label: "3 LIVE", tone: "alert" },
    title: "경기 운영 센터",
    subtitle: "현장 체크인, 노쇼, 일정 변경 등 매치 흐름을 한눈에 파악합니다.",
  },
  { type: "section", id: "community", label: "커뮤니티 인텔리전스" },
  {
    type: "link",
    id: "members",
    label: "회원 인텔",
    description: "세그먼트 · 활동 로그",
    icon: Users2,
    path: "/admin/members",
    badge: { label: "+128", tone: "info" },
    title: "회원 운영 현황",
    subtitle: "가입 추이, 리텐션, 신고 이력 등 커뮤니티 상태를 추적합니다.",
  },
  {
    type: "link",
    id: "teams",
    label: "픽업 팀 인사이트",
    description: "팀 컨디션 · 지원 요청",
    icon: PanelsTopLeft,
    path: "/admin/teams",
    title: "팀 운영 보드",
    subtitle: "핵심 참여팀, 지원 요청, 노쇼 경보를 빠르게 확인합니다.",
  },
  { type: "section", id: "content", label: "콘텐츠 & 커뮤니케이션" },
  {
    type: "link",
    id: "content",
    label: "공지·콘텐츠 허브",
    description: "공지 · 게시물 · 메시지",
    icon: Megaphone,
    path: "/admin/content",
    badge: { label: "검수 6", tone: "warning" },
    title: "콘텐츠 검수 센터",
    subtitle: "공지, 게시물, 발송 기록을 관리하고 반응 데이터를 확인합니다.",
  },
  { type: "section", id: "compliance", label: "신고 · 컴플라이언스" },
  {
    type: "link",
    id: "reports",
    label: "신고 & 제재",
    description: "SLA · 반복 신고자",
    icon: ShieldCheck,
    path: "/admin/reports",
    badge: { label: "SLA 4", tone: "alert" },
    title: "신고 처리 현황",
    subtitle: "긴급 신고와 후속 제재까지 전 과정을 추적합니다.",
  },
  { type: "section", id: "system", label: "시스템 & 설정" },
  {
    type: "link",
    id: "system",
    label: "시스템 모니터링",
    description: "서비스 헬스 · 인시던트",
    icon: ServerCog,
    path: "/admin/system",
    title: "시스템 운영 지표",
    subtitle: "API 성능, 장애 이벤트, 배포 로그를 실시간으로 모니터링합니다.",
  },
  {
    type: "link",
    id: "settings",
    label: "운영 설정",
    description: "자동화 · 외부 연동",
    icon: Settings2,
    path: "/admin/settings",
    title: "운영 정책 설정",
    subtitle: "승인 단계, 자동화 규칙, 통합 연동을 관리합니다.",
  },
];

export const adminNavLinks: AdminNavLink[] = adminNavEntries.filter(
  (entry): entry is AdminNavLink => entry.type === "link",
);

export const sidebarMetrics: SidebarMetric[] = [
  { label: "오늘 매치", value: "6" },
  { label: "관심 팀", value: "5", tone: "warning" },
  { label: "알림", value: "2", tone: "info" },
];

