server:
  port: 8086

spring:
  application:
    name: match-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sportshub_match_db}
    username: ${SPRING_DATASOURCE_USERNAME:sportshub_user}
    password: ${SPRING_DATASOURCE_PASSWORD:changeme}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: ${FLYWAY_CLEAN_ON_VALIDATION_ERROR:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sportshub.match: DEBUG
    org.flywaydb: DEBUG
